# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mmullis-flay}
  s.version = "1.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Davis", "Seattle.rb", "Michael Mullis"]
  s.date = %q{2011-03-04}
  s.default_executable = %q{flay}
  s.description = %q{Flay fork with modifications to run on 1.9.2}
  s.email = %q{michael@mullistechnologies.com}
  s.executables = ["flay"]
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "History.txt",
    "Manifest.txt",
    "README.txt",
    "Rakefile",
    "VERSION",
    "bin/flay",
    "lib/flay.rb",
    "lib/flay_erb.rb",
    "lib/flay_task.rb",
    "lib/gauntlet_flay.rb",
    "test/test_flay.rb"
  ]
  s.homepage = %q{http://github.com/mmullis/flay}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.3}
  s.summary = %q{Flay fork with 1.9.2 Repairs}
  s.test_files = [
    "test/test_flay.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sexp_processor>, ["~> 3.0"])
      s.add_runtime_dependency(%q<ruby_parser>, ["~> 2.0"])
    else
      s.add_dependency(%q<sexp_processor>, ["~> 3.0"])
      s.add_dependency(%q<ruby_parser>, ["~> 2.0"])
    end
  else
    s.add_dependency(%q<sexp_processor>, ["~> 3.0"])
    s.add_dependency(%q<ruby_parser>, ["~> 2.0"])
  end
end

